// Errors
export const GET_ERRORS = 'GET_ERRORS' 

// Authentication
export const USER_LOADING = 'USER_LOADING' 
export const USER_LOADED = 'USER_LOADED' 
export const AUTH_ERROR = 'AUTH_ERROR' 

// Authentication
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS' 
export const LOGIN_FAIL = 'LOGIN_FAIL' 
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS' 
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL' 

// Favorites
export const ADD_FAVORITE = 'ADD_FAVORITE'
export const GET_FAVORITES = 'GET_FAVORITES'
export const DELETE_FAVORITES = 'DELETE_FAVORITES'
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE'
export const UPDATE_FAVORITES = 'UPDATE_FAVORITES'
export const CREATE_FAVORITES = 'CREATE_FAVORITES'
export const FAVORITES_LOADING = 'FAVORITES_LOADING' 
export const FAVORITES_LOADED = 'FAVORITES_LOADED'
export const FAVORITES_LOADING_ERROR = 'FAVORITES_LOADING_ERROR'

// Subway
export const SET_STATIONS = 'SET_STATIONS'
export const SET_FILTERED_STATIONS = 'SET_FILTERED_STATIONS'
export const SET_NEARBY_STATIONS = 'SET_NEARBY_STATIONS'
export const SET_STATION_DETAIL = 'SET_STATION_DETAIL' 
export const SET_MARKERS = 'SET_MARKERS' 
export const SET_SERVICE_INFORMATION = 'SET_SERVICE_INFORMATION'
export const SET_TIME_UPDATED = 'SET_TIME_UPDATED'
export const SET_USER_COORDINATES = 'SET_USER_COORDINATES'
export const HANDLE_STATION_CLICK = 'HANDLE_STATION_CLICK'
