# Generated by Django 2.2.5 on 2019-10-03 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('6 express', '6 express'), ('7', '7'), ('7 express', '7 express'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('J', 'J'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('W', 'W'), ('Z', 'Z')], help_text='Subway Line Name', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_stations', models.ManyToManyField(to='favorites.Line')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoriteLines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
