# Generated by Django 2.2.5 on 2019-10-04 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritelines',
            options={'verbose_name_plural': 'FavoriteLines'},
        ),
    ]
