# Generated by Django 2.2.5 on 2019-10-04 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_auto_20191003_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritelines',
            old_name='favorite_stations',
            new_name='favorite_lines',
        ),
    ]
