# Generated by Django 2.2.5 on 2019-10-04 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0004_auto_20191003_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritelines',
            old_name='favoriteLines',
            new_name='favorite_lines',
        ),
    ]
