# Generated by Django 2.2.5 on 2019-10-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0006_auto_20191003_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(help_text='Subway Line Name', max_length=9),
        ),
    ]
