# Generated by Django 2.2.5 on 2019-10-04 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorites', '0008_auto_20191003_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritelines',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='favoritelines',
            name='name',
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subway Line Name', max_length=9)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
