# Generated by Django 2.2.5 on 2019-10-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0009_auto_20191003_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritelines',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='line',
            name='owner',
        ),
        migrations.AddField(
            model_name='favoritelines',
            name='lines',
            field=models.ManyToManyField(to='favorites.Line'),
        ),
    ]
