# Generated by Django 2.2.5 on 2019-10-04 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0010_auto_20191003_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritelines',
            old_name='owner',
            new_name='user',
        ),
    ]
