# Generated by Django 2.2.5 on 2019-10-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0011_auto_20191003_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelines',
            name='lines',
            field=models.ManyToManyField(blank=True, related_name='lines', to='favorites.Line'),
        ),
    ]
